[["file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/yaml/Exception/RuntimeException.php",{"_uri":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/yaml/Exception/RuntimeException.php","_root":{"kind":4096,"name":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/yaml/Exception/RuntimeException.php","location":{"uriHash":480739183,"range":{"start":{"line":0,"character":0},"end":{"line":21,"character":0}}},"children":[{"kind":512,"name":"Symfony\\Component\\Yaml\\Exception","location":{"uriHash":480739183,"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":43}}}},{"kind":1,"name":"Symfony\\Component\\Yaml\\Exception\\RuntimeException","location":{"uriHash":480739183,"range":{"start":{"line":18,"character":0},"end":{"line":20,"character":1}}},"children":[],"associated":[{"kind":1,"name":"RuntimeException"},{"kind":2,"name":"Symfony\\Component\\Yaml\\Exception\\ExceptionInterface"}],"doc":{"description":"Exception class thrown when an error occurs during parsing.","type":""},"modifiers":0}]},"_hash":480739183}]]