[["file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php",{"_uri":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php","_root":{"kind":4096,"name":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php","location":{"uriHash":728672294,"range":{"start":{"line":0,"character":0},"end":{"line":161,"character":0}}},"children":[{"kind":512,"name":"Illuminate\\Foundation\\Bootstrap","location":{"uriHash":728672294,"range":{"start":{"line":2,"character":0},"end":{"line":2,"character":42}}}},{"kind":1,"name":"Exception","location":{"uriHash":728672294,"range":{"start":{"line":4,"character":4},"end":{"line":4,"character":13}}},"modifiers":4096,"associated":[{"kind":1,"name":"Exception"}]},{"kind":1,"name":"ErrorException","location":{"uriHash":728672294,"range":{"start":{"line":5,"character":4},"end":{"line":5,"character":18}}},"modifiers":4096,"associated":[{"kind":1,"name":"ErrorException"}]},{"kind":1,"name":"ExceptionHandler","location":{"uriHash":728672294,"range":{"start":{"line":6,"character":4},"end":{"line":6,"character":47}}},"modifiers":4096,"associated":[{"kind":1,"name":"Illuminate\\Contracts\\Debug\\ExceptionHandler"}]},{"kind":1,"name":"Application","location":{"uriHash":728672294,"range":{"start":{"line":7,"character":4},"end":{"line":7,"character":47}}},"modifiers":4096,"associated":[{"kind":1,"name":"Illuminate\\Contracts\\Foundation\\Application"}]},{"kind":1,"name":"ConsoleOutput","location":{"uriHash":728672294,"range":{"start":{"line":8,"character":4},"end":{"line":8,"character":50}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"kind":1,"name":"FatalErrorException","location":{"uriHash":728672294,"range":{"start":{"line":9,"character":4},"end":{"line":9,"character":57}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\Debug\\Exception\\FatalErrorException"}]},{"kind":1,"name":"FatalThrowableError","location":{"uriHash":728672294,"range":{"start":{"line":10,"character":4},"end":{"line":10,"character":57}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError"}]},{"kind":1,"name":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions","location":{"uriHash":728672294,"range":{"start":{"line":12,"character":0},"end":{"line":160,"character":1}}},"children":[{"kind":16,"name":"$app","location":{"uriHash":728672294,"range":{"start":{"line":19,"character":14},"end":{"line":19,"character":18}}},"doc":{"description":"","type":"Illuminate\\Contracts\\Foundation\\Application"},"modifiers":2,"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"bootstrap","location":{"uriHash":728672294,"range":{"start":{"line":27,"character":4},"end":{"line":42,"character":5}}},"doc":{"description":"Bootstrap the given application.","type":"void"},"modifiers":1,"type":"","children":[{"kind":128,"name":"$app","location":{"uriHash":728672294,"range":{"start":{"line":27,"character":30},"end":{"line":27,"character":46}}},"type":"Illuminate\\Contracts\\Foundation\\Application","doc":{"description":"","type":"Illuminate\\Contracts\\Foundation\\Application"},"scope":"bootstrap"}],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"handleError","location":{"uriHash":728672294,"range":{"start":{"line":56,"character":4},"end":{"line":61,"character":5}}},"doc":{"description":"Convert PHP errors to ErrorException instances.","type":"void"},"modifiers":1,"type":"","children":[{"kind":128,"name":"$level","location":{"uriHash":728672294,"range":{"start":{"line":56,"character":32},"end":{"line":56,"character":38}}},"doc":{"description":"","type":"int"},"scope":"handleError"},{"kind":128,"name":"$message","location":{"uriHash":728672294,"range":{"start":{"line":56,"character":40},"end":{"line":56,"character":48}}},"doc":{"description":"","type":"string"},"scope":"handleError"},{"kind":128,"name":"$file","location":{"uriHash":728672294,"range":{"start":{"line":56,"character":50},"end":{"line":56,"character":60}}},"doc":{"description":"","type":"string"},"value":"''","scope":"handleError"},{"kind":128,"name":"$line","location":{"uriHash":728672294,"range":{"start":{"line":56,"character":62},"end":{"line":56,"character":71}}},"doc":{"description":"","type":"int"},"value":"0","scope":"handleError"},{"kind":128,"name":"$context","location":{"uriHash":728672294,"range":{"start":{"line":56,"character":73},"end":{"line":56,"character":86}}},"doc":{"description":"","type":"array"},"value":"[]","scope":"handleError"}],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"handleException","location":{"uriHash":728672294,"range":{"start":{"line":73,"character":4},"end":{"line":90,"character":5}}},"doc":{"description":"Handle an uncaught exception from the application.\n\nNote: Most exceptions can be handled via the try / catch block in\nthe HTTP and Console kernels. But, fatal error exceptions must\nbe handled differently since they are not normal exceptions.","type":"void"},"modifiers":1,"type":"","children":[{"kind":128,"name":"$e","location":{"uriHash":728672294,"range":{"start":{"line":73,"character":36},"end":{"line":73,"character":38}}},"doc":{"description":"","type":"Throwable"},"scope":"handleException"}],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"renderForConsole","location":{"uriHash":728672294,"range":{"start":{"line":98,"character":4},"end":{"line":101,"character":5}}},"doc":{"description":"Render an exception to the console.","type":"void"},"modifiers":2,"type":"","children":[{"kind":128,"name":"$e","location":{"uriHash":728672294,"range":{"start":{"line":98,"character":40},"end":{"line":98,"character":52}}},"type":"Exception","doc":{"description":"","type":"Exception"},"scope":"renderForConsole"}],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"renderHttpResponse","location":{"uriHash":728672294,"range":{"start":{"line":109,"character":4},"end":{"line":112,"character":5}}},"doc":{"description":"Render an exception as an HTTP response and send it.","type":"void"},"modifiers":2,"type":"","children":[{"kind":128,"name":"$e","location":{"uriHash":728672294,"range":{"start":{"line":109,"character":42},"end":{"line":109,"character":54}}},"type":"Exception","doc":{"description":"","type":"Exception"},"scope":"renderHttpResponse"}],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"handleShutdown","location":{"uriHash":728672294,"range":{"start":{"line":119,"character":4},"end":{"line":124,"character":5}}},"doc":{"description":"Handle the PHP shutdown event.","type":"void"},"modifiers":1,"type":"","children":[],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"fatalExceptionFromError","location":{"uriHash":728672294,"range":{"start":{"line":133,"character":4},"end":{"line":138,"character":5}}},"doc":{"description":"Create a new fatal exception instance from an error array.","type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException"},"modifiers":2,"type":"","children":[{"kind":128,"name":"$error","location":{"uriHash":728672294,"range":{"start":{"line":133,"character":47},"end":{"line":133,"character":59}}},"type":"array","doc":{"description":"","type":"array"},"scope":"fatalExceptionFromError"},{"kind":128,"name":"$traceOffset","location":{"uriHash":728672294,"range":{"start":{"line":133,"character":61},"end":{"line":133,"character":80}}},"doc":{"description":"","type":"int|null"},"value":"null","scope":"fatalExceptionFromError"}],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"isFatal","location":{"uriHash":728672294,"range":{"start":{"line":146,"character":4},"end":{"line":149,"character":5}}},"doc":{"description":"Determine if the error type is fatal.","type":"bool"},"modifiers":2,"type":"","children":[{"kind":128,"name":"$type","location":{"uriHash":728672294,"range":{"start":{"line":146,"character":31},"end":{"line":146,"character":36}}},"doc":{"description":"","type":"int"},"scope":"isFatal"}],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"},{"kind":32,"name":"getExceptionHandler","location":{"uriHash":728672294,"range":{"start":{"line":156,"character":4},"end":{"line":159,"character":5}}},"doc":{"description":"Get an instance of the exception handler.","type":"Illuminate\\Contracts\\Debug\\ExceptionHandler"},"modifiers":2,"type":"","children":[],"scope":"Illuminate\\Foundation\\Bootstrap\\HandleExceptions"}],"associated":[],"modifiers":0}]},"_hash":728672294}]]