[["file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/http-kernel/Event/GetResponseForExceptionEvent.php",{"_uri":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/http-kernel/Event/GetResponseForExceptionEvent.php","_root":{"kind":4096,"name":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/http-kernel/Event/GetResponseForExceptionEvent.php","location":{"uriHash":761511519,"range":{"start":{"line":0,"character":0},"end":{"line":90,"character":0}}},"children":[{"kind":512,"name":"Symfony\\Component\\HttpKernel\\Event","location":{"uriHash":761511519,"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":45}}}},{"kind":1,"name":"Request","location":{"uriHash":761511519,"range":{"start":{"line":13,"character":4},"end":{"line":13,"character":44}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\HttpFoundation\\Request"}]},{"kind":1,"name":"HttpKernelInterface","location":{"uriHash":761511519,"range":{"start":{"line":14,"character":4},"end":{"line":14,"character":52}}},"modifiers":4096,"associated":[{"kind":1,"name":"Symfony\\Component\\HttpKernel\\HttpKernelInterface"}]},{"kind":1,"name":"Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent","location":{"uriHash":761511519,"range":{"start":{"line":29,"character":0},"end":{"line":89,"character":1}}},"children":[{"kind":16,"name":"$exception","location":{"uriHash":761511519,"range":{"start":{"line":36,"character":12},"end":{"line":36,"character":22}}},"doc":{"description":"","type":"Exception"},"modifiers":4,"scope":"Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"},{"kind":16,"name":"$allowCustomResponseCode","location":{"uriHash":761511519,"range":{"start":{"line":41,"character":12},"end":{"line":41,"character":44}}},"doc":{"description":"","type":"bool"},"value":"","modifiers":4,"scope":"Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"},{"kind":32,"name":"__construct","location":{"uriHash":761511519,"range":{"start":{"line":43,"character":4},"end":{"line":48,"character":5}}},"doc":{"description":"","type":""},"modifiers":1,"type":"","children":[{"kind":128,"name":"$kernel","location":{"uriHash":761511519,"range":{"start":{"line":43,"character":32},"end":{"line":43,"character":59}}},"type":"Symfony\\Component\\HttpKernel\\HttpKernelInterface","scope":"__construct"},{"kind":128,"name":"$request","location":{"uriHash":761511519,"range":{"start":{"line":43,"character":61},"end":{"line":43,"character":77}}},"type":"Symfony\\Component\\HttpFoundation\\Request","scope":"__construct"},{"kind":128,"name":"$requestType","location":{"uriHash":761511519,"range":{"start":{"line":43,"character":79},"end":{"line":43,"character":91}}},"scope":"__construct"},{"kind":128,"name":"$e","location":{"uriHash":761511519,"range":{"start":{"line":43,"character":93},"end":{"line":43,"character":106}}},"type":"Exception","scope":"__construct"}],"scope":"Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"},{"kind":32,"name":"getException","location":{"uriHash":761511519,"range":{"start":{"line":55,"character":4},"end":{"line":58,"character":5}}},"doc":{"description":"Returns the thrown exception.","type":"Exception"},"modifiers":1,"type":"","children":[],"scope":"Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"},{"kind":32,"name":"setException","location":{"uriHash":761511519,"range":{"start":{"line":67,"character":4},"end":{"line":70,"character":5}}},"doc":{"description":"Replaces the thrown exception.\n\nThis exception will be thrown if no response is set in the event.","type":""},"modifiers":1,"type":"","children":[{"kind":128,"name":"$exception","location":{"uriHash":761511519,"range":{"start":{"line":67,"character":33},"end":{"line":67,"character":54}}},"type":"Exception","doc":{"description":"The thrown exception","type":"Exception"},"scope":"setException"}],"scope":"Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"},{"kind":32,"name":"allowCustomResponseCode","location":{"uriHash":761511519,"range":{"start":{"line":75,"character":4},"end":{"line":78,"character":5}}},"doc":{"description":"Mark the event as allowing a custom response code.","type":""},"modifiers":1,"type":"","children":[],"scope":"Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"},{"kind":32,"name":"isAllowingCustomResponseCode","location":{"uriHash":761511519,"range":{"start":{"line":85,"character":4},"end":{"line":88,"character":5}}},"doc":{"description":"Returns true if the event allows a custom response code.","type":"bool"},"modifiers":1,"type":"","children":[],"scope":"Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent"}],"associated":[{"kind":1,"name":"Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"}],"doc":{"description":"Allows to create a response for a thrown exception.\n\nCall setResponse() to set the response that will be returned for the\ncurrent request. The propagation of this event is stopped as soon as a\nresponse is set.\n\nYou can also call setException() to replace the thrown exception. This\nexception will be thrown if no response is set during processing of this\nevent.","type":""},"modifiers":0}]},"_hash":761511519}]]