[["file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/yaml/Exception/DumpException.php",{"_uri":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/yaml/Exception/DumpException.php","_root":{"kind":4096,"name":"file:///home/jfvilladiego/proyectos_laravel/cotizaciones_vcb_laravel/vendor/symfony/yaml/Exception/DumpException.php","location":{"uriHash":1611048341,"range":{"start":{"line":0,"character":0},"end":{"line":21,"character":0}}},"children":[{"kind":512,"name":"Symfony\\Component\\Yaml\\Exception","location":{"uriHash":1611048341,"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":43}}}},{"kind":1,"name":"Symfony\\Component\\Yaml\\Exception\\DumpException","location":{"uriHash":1611048341,"range":{"start":{"line":18,"character":0},"end":{"line":20,"character":1}}},"children":[],"associated":[{"kind":1,"name":"Symfony\\Component\\Yaml\\Exception\\RuntimeException"}],"doc":{"description":"Exception class thrown when an error occurs during dumping.","type":""},"modifiers":0}]},"_hash":1611048341}]]